# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MHBS7dhBctsVp8jk-rWODcHYlxzXryzy
"""

# ==========================================================
# CREDIT EDA CASE STUDY - COMPLETE ONE SHOT CODE
# ==========================================================

# ===============================
# IMPORT LIBRARIES
# ===============================

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

plt.style.use("ggplot")
sns.set(font_scale=1.0)

# ===============================
# LOAD DATA
# ===============================

application = pd.read_csv("application_data.csv")
previous = pd.read_csv("previous_application.csv")

# ===============================
# BASIC INFORMATION
# ===============================

print("="*60)
print("APPLICATION DATA")
print("="*60)

print(application.head())
print(application.shape)
print(application.info())

print("\nMissing Values")
print(application.isnull().sum())

print("\nDuplicate Rows")
print(application.duplicated().sum())

print("="*60)
print("PREVIOUS APPLICATION")
print("="*60)

print(previous.head())
print(previous.shape)
print(previous.info())

# ===============================
# MISSING VALUE PERCENTAGE
# ===============================

missing = application.isnull().sum()/len(application)*100
missing = missing.sort_values(ascending=False)

missing_df = pd.DataFrame({
    "Column":missing.index,
    "Missing %":missing.values
})

print(missing_df.head(30))

plt.figure(figsize=(10,8))
sns.barplot(
    x="Missing %",
    y="Column",
    data=missing_df.head(20)
)
plt.title("Top Missing Columns")
plt.show()

# ===============================
# REMOVE COLUMNS >40% MISSING
# ===============================

application = application.loc[:,application.isnull().mean()<0.40]

print("New Shape :",application.shape)

# ===============================
# NUMERICAL SUMMARY
# ===============================

print(application.describe())

# ===============================
# CATEGORICAL SUMMARY
# ===============================

print(application.describe(include='object'))

# ==========================================================
# TARGET DISTRIBUTION
# ==========================================================

plt.figure(figsize=(6,4))

sns.countplot(
    x="TARGET",
    data=application
)

plt.title("Target Distribution")
plt.show()

print(application["TARGET"].value_counts(normalize=True)*100)

# ==========================================================
# NUMERIC DISTRIBUTION
# ==========================================================

numeric_cols = application.select_dtypes(include=np.number).columns

for col in numeric_cols[:10]:

    plt.figure(figsize=(8,4))

    sns.histplot(
        application[col],
        kde=True
    )

    plt.title(col)

    plt.show()

# ==========================================================
# BOXPLOTS
# ==========================================================

box_cols = [
    'AMT_INCOME_TOTAL',
    'AMT_CREDIT',
    'AMT_ANNUITY'
]

for col in box_cols:

    if col in application.columns:

        plt.figure(figsize=(6,3))

        sns.boxplot(
            x=application[col]
        )

        plt.title(col)

        plt.show()

# ==========================================================
# CATEGORICAL COUNTPLOTS
# ==========================================================

cat_cols = [

'CODE_GENDER',

'NAME_INCOME_TYPE',

'NAME_EDUCATION_TYPE',

'NAME_FAMILY_STATUS',

'NAME_HOUSING_TYPE'

]

for col in cat_cols:

    if col in application.columns:

        plt.figure(figsize=(8,4))

        sns.countplot(
            y=col,
            data=application,
            order=application[col].value_counts().index
        )

        plt.title(col)

        plt.show()

# ==========================================================
# BIVARIATE ANALYSIS
# ==========================================================

# Income vs Target

plt.figure(figsize=(7,5))

sns.boxplot(
    x='TARGET',
    y='AMT_INCOME_TOTAL',
    data=application
)

plt.show()

# Credit vs Target

plt.figure(figsize=(7,5))

sns.boxplot(
    x='TARGET',
    y='AMT_CREDIT',
    data=application
)

plt.show()

# Annuity vs Target

plt.figure(figsize=(7,5))

sns.boxplot(
    x='TARGET',
    y='AMT_ANNUITY',
    data=application
)

plt.show()

# ==========================================================
# TARGET VS CATEGORICAL VARIABLES
# ==========================================================

bivariate_cols=[

'CODE_GENDER',

'NAME_EDUCATION_TYPE',

'NAME_INCOME_TYPE',

'NAME_FAMILY_STATUS',

'NAME_HOUSING_TYPE'

]

for col in bivariate_cols:

    if col in application.columns:

        plt.figure(figsize=(8,5))

        sns.countplot(

            y=col,

            hue='TARGET',

            data=application

        )

        plt.title(col)

        plt.show()

# ==========================================================
# DEFAULT RATE TABLES
# ==========================================================

for col in bivariate_cols:

    if col in application.columns:

        print("\n",col)

        table=pd.crosstab(

            application[col],

            application["TARGET"],

            normalize="index"

        )*100

        print(table)

# ==========================================================
# CORRELATION HEATMAP
# ==========================================================

corr=application.select_dtypes(include=np.number).corr()

plt.figure(figsize=(18,14))

sns.heatmap(

    corr,

    cmap='coolwarm',

    center=0

)

plt.title("Correlation Heatmap")

plt.show()

# ==========================================================
# PREVIOUS APPLICATION ANALYSIS
# ==========================================================

print(previous.head())

print(previous["NAME_CONTRACT_STATUS"].value_counts())

plt.figure(figsize=(8,5))

sns.countplot(

    y='NAME_CONTRACT_STATUS',

    data=previous,

    order=previous["NAME_CONTRACT_STATUS"].value_counts().index

)

plt.title("Previous Loan Status")

plt.show()

# Loan Type

plt.figure(figsize=(7,5))

sns.countplot(

    y='NAME_CONTRACT_TYPE',

    data=previous

)

plt.show()

# Purpose

plt.figure(figsize=(12,8))

sns.countplot(

    y='NAME_CASH_LOAN_PURPOSE',

    data=previous,

    order=previous["NAME_CASH_LOAN_PURPOSE"].value_counts().head(15).index

)

plt.show()

# ==========================================================
# MERGE BOTH DATASETS
# ==========================================================

merged=pd.merge(

    application,

    previous,

    on='SK_ID_CURR',

    how='left'

)

print(merged.shape)

# ==========================================================
# BUSINESS QUESTIONS
# ==========================================================

print("="*60)
print("Average Income by Target")
print("="*60)

print(

application.groupby("TARGET")["AMT_INCOME_TOTAL"].mean()

)

print("="*60)
print("Average Credit by Target")
print("="*60)

print(

application.groupby("TARGET")["AMT_CREDIT"].mean()

)

print("="*60)
print("Education vs Target")
print("="*60)

print(

pd.crosstab(

application["NAME_EDUCATION_TYPE"],

application["TARGET"],

normalize="index"

)*100

)

print("="*60)
print("Income Type vs Target")
print("="*60)

print(

pd.crosstab(

application["NAME_INCOME_TYPE"],

application["TARGET"],

normalize="index"

)*100

)

print("="*60)
print("Gender vs Target")
print("="*60)

print(

pd.crosstab(

application["CODE_GENDER"],

application["TARGET"],

normalize="index"

)*100

)

print("="*60)
print("Family Status vs Target")
print("="*60)

print(

pd.crosstab(

application["NAME_FAMILY_STATUS"],

application["TARGET"],

normalize="index"

)*100

)

# ==========================================================
# TOP CORRELATED FEATURES
# ==========================================================

corr_target = application.corr(numeric_only=True)["TARGET"].sort_values(ascending=False)

print("="*60)
print("Top Positive Correlation with TARGET")
print("="*60)

print(corr_target.head(15))

print("="*60)
print("Top Negative Correlation with TARGET")
print("="*60)

print(corr_target.tail(15))

# ==========================================================
# SAVE CLEAN DATA
# ==========================================================

application.to_csv("application_clean.csv",index=False)
previous.to_csv("previous_clean.csv",index=False)

print("="*60)
print("EDA COMPLETED SUCCESSFULLY")
print("="*60)