# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MHBS7dhBctsVp8jk-rWODcHYlxzXryzy
"""

 

import pandas as pd

# Create Excel Writer
writer = pd.ExcelWriter(
    "Credit_EDA_Report.xlsx",
    engine="openpyxl"
)

 

summary = pd.DataFrame({
    "Metric":[
        "Rows",
        "Columns",
        "Duplicate Rows",
        "Total Missing Values"
    ],
    "Value":[
        application.shape[0],
        application.shape[1],
        application.duplicated().sum(),
        application.isnull().sum().sum()
    ]
})

summary.to_excel(
    writer,
    sheet_name="Dataset Summary",
    index=False
)

 

column_info = pd.DataFrame({
    "Column":application.columns,
    "Data Type":application.dtypes.values,
    "Missing Count":application.isnull().sum().values,
    "Missing %":(
        application.isnull().mean()*100
    ).round(2),
    "Unique Values":application.nunique().values
})

column_info.to_excel(
    writer,
    sheet_name="Column Info",
    index=False
)

 

application.describe().T.to_excel(
    writer,
    sheet_name="Numerical Summary"
)

 

application.describe(include="object").T.to_excel(
    writer,
    sheet_name="Categorical Summary"
)

 

missing = pd.DataFrame({
    "Missing Count":application.isnull().sum(),
    "Missing %":(
        application.isnull().mean()*100
    ).round(2)
})

missing = missing.sort_values(
    by="Missing %",
    ascending=False
)

missing.to_excel(
    writer,
    sheet_name="Missing Values"
)

 

target = application["TARGET"].value_counts()

target_df = pd.DataFrame({
    "Target":target.index,
    "Count":target.values,
    "Percentage":(
        target.values/target.sum()*100
    ).round(2)
})

target_df.to_excel(
    writer,
    sheet_name="Target Distribution",
    index=False
)
 

corr = application.corr(numeric_only=True)

corr.to_excel(
    writer,
    sheet_name="Correlation Matrix"
)

 

gender = pd.crosstab(
    application["CODE_GENDER"],
    application["TARGET"],
    normalize="index"
)*100

gender.to_excel(
    writer,
    sheet_name="Gender Analysis"
)

 

education = pd.crosstab(
    application["NAME_EDUCATION_TYPE"],
    application["TARGET"],
    normalize="index"
)*100

education.to_excel(
    writer,
    sheet_name="Education Analysis"
)

 

income = pd.crosstab(
    application["NAME_INCOME_TYPE"],
    application["TARGET"],
    normalize="index"
)*100

income.to_excel(
    writer,
    sheet_name="Income Type"
)

 

family = pd.crosstab(
    application["NAME_FAMILY_STATUS"],
    application["TARGET"],
    normalize="index"
)*100

family.to_excel(
    writer,
    sheet_name="Family Status"
)

# ==========================================================
# SHEET 12 : HOUSING TYPE
# ==========================================================

if "NAME_HOUSING_TYPE" in application.columns:

    housing = pd.crosstab(
        application["NAME_HOUSING_TYPE"],
        application["TARGET"],
        normalize="index"
    )*100

    housing.to_excel(
        writer,
        sheet_name="Housing Type"
    )

# ==========================================================
# SHEET 13 : TOP CORRELATED FEATURES
# ==========================================================

target_corr = application.corr(
    numeric_only=True
)["TARGET"].sort_values(
    ascending=False
)

target_corr.to_excel(
    writer,
    sheet_name="Target Correlation"
)

# ==========================================================
# SHEET 14 : PREVIOUS APPLICATION STATUS
# ==========================================================

status = previous["NAME_CONTRACT_STATUS"].value_counts()

status.to_excel(
    writer,
    sheet_name="Previous Status"
)

# ==========================================================
# SHEET 15 : CONTRACT TYPE
# ==========================================================

contract = previous["NAME_CONTRACT_TYPE"].value_counts()

contract.to_excel(
    writer,
    sheet_name="Contract Type"
)

# ==========================================================
# SHEET 16 : LOAN PURPOSE
# ==========================================================

purpose = previous[
    "NAME_CASH_LOAN_PURPOSE"
].value_counts()

purpose.to_excel(
    writer,
    sheet_name="Loan Purpose"
)

# ==========================================================
# SHEET 17 : MERGED DATA SUMMARY
# ==========================================================

merged = pd.merge(
    application,
    previous,
    on="SK_ID_CURR",
    how="left"
)

merged_summary = pd.DataFrame({
    "Rows":[merged.shape[0]],
    "Columns":[merged.shape[1]]
})

merged_summary.to_excel(
    writer,
    sheet_name="Merged Summary",
    index=False
)

# ==========================================================
# SHEET 18 : BUSINESS INSIGHTS
# ==========================================================

business = pd.DataFrame({

"Metric":[

"Average Income - Non Defaulter",

"Average Income - Defaulter",

"Average Credit - Non Defaulter",

"Average Credit - Defaulter"

],

"Value":[

application[application.TARGET==0]["AMT_INCOME_TOTAL"].mean(),

application[application.TARGET==1]["AMT_INCOME_TOTAL"].mean(),

application[application.TARGET==0]["AMT_CREDIT"].mean(),

application[application.TARGET==1]["AMT_CREDIT"].mean()

]

})

business.to_excel(
    writer,
    sheet_name="Business Insights",
    index=False
)

# ==========================================================
# SAVE REPORT
# ==========================================================

writer.close()

print("="*60)
print("Credit_EDA_Report.xlsx GENERATED SUCCESSFULLY")
print("="*60)