# -*- coding: utf-8 -*-
"""second test que 2 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MHBS7dhBctsVp8jk-rWODcHYlxzXryzy
"""

import pandas as pd
from sqlalchemy import create_engine, text



# Uncomment the appropriate one

# CSV
df = pd.read_csv("your_file.csv")

# Excel
# df = pd.read_excel("your_file.xlsx")

print("Shape :", df.shape)



print("\nMemory Usage Before Optimization")
before = df.memory_usage(deep=True).sum() / 1024**2
print(f"{before:.2f} MB")



for col in df.columns:

    # Convert object columns having low cardinality into category
    if df[col].dtype == "object":

        if df[col].nunique() / len(df) < 0.50:
            df[col] = df[col].astype("category")

    # Integer Optimization
    elif str(df[col].dtype).startswith("int"):
        df[col] = pd.to_numeric(df[col], downcast="integer")

    # Float Optimization
    elif str(df[col].dtype).startswith("float"):
        df[col] = pd.to_numeric(df[col], downcast="float")

print("\nOptimized Data Types")
print(df.dtypes)



print("\nMemory Usage After Optimization")

after = df.memory_usage(deep=True).sum() / 1024**2

print(f"{after:.2f} MB")

print(f"\nMemory Reduced : {before-after:.2f} MB")

print(f"Reduction Percentage : {((before-after)/before)*100:.2f}%")



username = "root"
password = "password"
host = "localhost"
port = 3306
database = "etl_db"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)



table_name = "loan_data"

index_name = "idx_customer"

with engine.begin() as conn:

    try:
        conn.execute(text(f"DROP INDEX {index_name} ON {table_name};"))
        print("Existing Index Dropped")
    except:
        print("Index Does Not Exist")


df.to_sql(
    table_name,
    engine,
    if_exists="append",
    index=False,
    chunksize=5000
)

print("Data Inserted Successfully")



# Change this column according to your dataset

index_column = "CustomerID"

with engine.begin() as conn:

    conn.execute(
        text(
            f"""
            CREATE INDEX {index_name}
            ON {table_name} ({index_column});
            """
        )
    )

print("Index Created Successfully")



with engine.connect() as conn:

    result = conn.execute(
        text(f"SELECT COUNT(*) FROM {table_name}")
    )

    print("\nTotal Records :", result.scalar())

print("\nETL Completed Successfully")