# -*- coding: utf-8 -*-
"""second test que 2 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MHBS7dhBctsVp8jk-rWODcHYlxzXryzy
"""

import pandas as pd
import os


file_path = '/content/Records Matching Task.xlsx'

# Load data1 and data2
df1 = pd.read_excel(file_path, sheet_name='data1')
df2 = pd.read_excel(file_path, sheet_name='data2')

print(f"Data1 Total Records: {len(df1)}")
print(f"Data2 Total Records: {len(df2)}")

# Create Composite Primary Key (Order ID + Product ID)
df1['Key'] = df1['Order ID'].astype(str).str.strip() + '_' + df1['Product ID'].astype(str).str.strip()
df2['Key'] = df2['Order ID'].astype(str).str.strip() + '_' + df2['Product ID'].astype(str).str.strip()

print(f"Unique keys in Data1: {df1['Key'].nunique()}")
print(f"Unique keys in Data2: {df2['Key'].nunique()}")

set_data1 = set(df1['Key'])
set_data2 = set(df2['Key'])

keys_in1_not2 = set_data1 - set_data2
records_in1_not2 = df1[df1['Key'].isin(keys_in1_not2)]

q1_answer = len(records_in1_not2)
print(f"Q1 Answer: Number of records present in data1 but missing in data2 = {q1_answer}")
records_in1_not2.head()

q3_answer = records_in2_not1['Qty'].sum()
print(f"Q3 Answer: Sum of total Qty of records missing in data1 but present in data2 = {q3_answer}")

combined_unique_keys = set_data1.union(set_data2)
q4_answer = len(combined_unique_keys)
print(f"Q4 Answer: Total number of unique records in combined dataset = {q4_answer}")

summary_df = pd.DataFrame({
    'Question No.': ['Q1', 'Q2', 'Q3', 'Q4'],
    'Requirement': [
        'Records present in Data1 but missing in Data2',
        'Records missing in Data1 but present in Data2',
        'Sum of total Qty of records missing in Data1 but present in Data2',
        'Total unique records in combined dataset (Data1 ∪ Data2)'
    ],
    'Calculated Value': [q1_answer, q2_answer, q3_answer, q4_answer]
})

summary_df